### ISSUE TITLE
PathRoot.h not found with Xcode MXTest Project

### ISSUE THREAD

**Issue by CoderAndCat** [webern/mx#121]
<img width="1146" alt="截屏2021-02-03 18 26 21" src="https://user-images.githubusercontent.com/22518690/106734118-9ef05e80-664d-11eb-97f8-6de3293cf4ff.png">

**Comment by webern** [comment]
Normally that file is generated by the cmake file. It defines a string that gives absolute paths so the test files can be found.

https://github.com/webern/mx/blob/a9fc36706eec038d4d68dd346c43dfe18184038a/CMakeLists.txt#L75...L89

You could create that file manually for now.

Are you using the checked-in Xcode project, i.e. https://github.com/webern/mx/tree/master/Xcode/mx.xcworkspace?
I don't remember how I handled PathRoot.h in the checked-in Xcode project... I think what happens is that, since I always use the Cmake project, PathRoot.h is generated for me. Then if I use the Xcode project, it happens to be there.

**Comment by CoderAndCat** [comment]
Yes, Im using the checked-in Xcode project. 
I only clone the mx to my computer. Does it cause?

**Comment by webern** [comment]
This issue is fixed with the PR I just merged.
