### ISSUE TITLE
use mx in iOS app, get problem

### ISSUE THREAD

**Issue by CoderAndCat** [webern/mx#123]
I had use cmake get libMx.a. and drop Sourcecode/private/mx/api to my project.  
and try to '#import "api/ApiCommon.h' to my project. then compile get a error like this:
<img width="994" alt="截屏2021-02-04 11 49 16" src="https://user-images.githubusercontent.com/22518690/106842444-07d3e700-66df-11eb-870f-0f3e9a7cde6e.png">

It seems that a function in the ApiCommon.h file cannot be accessed.

**Comment by webern** [comment]
You should add `Sourcode/include/mx` to your project, not `Sourcecode/private/mx/api`.

**Comment by CoderAndCat** [comment]
hank you, I fixed it.
I try "#import "mx/api/ApiCommon.h"" . also error when compile.
<img width="1393" alt="截屏2021-02-04 14 00 50" src="https://user-images.githubusercontent.com/22518690/106851565-7326b480-66f1-11eb-90fa-0010f36f1525.png">

This is my xcode configuration for c++
<img width="900" alt="截屏2021-02-04 14 03 16" src="https://user-images.githubusercontent.com/22518690/106851719-bed95e00-66f1-11eb-9676-8b4c877f8f28.png">

**Comment by webern** [comment]
Now I think you're back to the problem where headers are being interpreted as C instead of C++.

Are you including an mx file from a .m file, a .mm file, or something else?

**Comment by CoderAndCat** [comment]
#import "mx/api/ApiCommon.h"  in a .mm file.

**Comment by CoderAndCat** [comment]
> Now I think you're back to the problem where headers are being interpreted as C instead of C++.
> 
> Are you including an mx file from a .m file, a .mm file, or something else?

#import "mx/api/ApiCommon.h" in a .mm file.

**Comment by webern** [comment]
Hmmm, ultimately what you are trying to do is use C++ code in an iOS project, which is a fairly common thing to do.

Xcode build settings are very complicated, and without access to the project it's going to be difficult to help you set it up. Maybe there's an issue with header search paths? Maybe your .mm file is being interpreted as Objective-C instead of C++?

Maybe I can try to set up an example iOS project, but it's not my area of expertise. I think I would probably do one of these things.

1) add the mx source code to my iOS project directly, or

2) add the existing mx Xcode project into my project and depend on its iOS framework target, or

3) build the iOS.framework target from the checked-in Xcode project, then add that and the headers to the iOS project.

Option 3 is what we did when we were working on the Komp iOS project. We chose option 3 because mx takes a while to compile and we didn't want to have to recompile frequently.

Option 1 seems like the simplest to me. Both Option 1 and 2 avoid the possibility of not having the right architecture compiled (when using the simulator, for example). Option 1 avoids having any dependency on someone else's complicated Xcode settings.

**Comment by CoderAndCat** [comment]
Thank you very much for spending time on my question.
Another way is to support'cocoapods'. Is it currently possible?

**Comment by webern** [comment]
I have not published anything on cocoapods.

Attached is a project that may help you. I will explain in the next message.

[mxios-example.zip](https://github.com/webern/mx/files/5929989/mxios-example.zip)

**Comment by webern** [comment]
- To create this project, I copied `mx/Sourcecode` into the ios project and renamed it `mx-sourcecode`. 
- I deleted these, they are not needed:
  - `Sourcecode/private/mxtest`
  - `Sourcecode/private/mx/examples`
- I added the mx-sourcecode to the Xcode iOS project.

My header and C++ settings look like this:
![Screen Shot 2021-02-04 at 7 06 48 PM](https://user-images.githubusercontent.com/6260372/106988104-bf8ae800-6723-11eb-8916-ba2443a96b25.png)

- I created a function named getXml() using a `.mm` file, but exporting it as `extern "C"` Swift cannot interact with C++, only with C.

![image](https://user-images.githubusercontent.com/6260372/106988292-450e9800-6724-11eb-8ab3-6fd0cdb9703e.png)


- I added that header to the `mxios-Bridging-Header.h` which made it available in Swift.

![image](https://user-images.githubusercontent.com/6260372/106988301-522b8700-6724-11eb-8df3-74b5684be28e.png)

- I called it in a swift file

![image](https://user-images.githubusercontent.com/6260372/106988316-5fe10c80-6724-11eb-9687-5953ae1a4d99.png)

- It worked

![image](https://user-images.githubusercontent.com/6260372/106988435-a20a4e00-6724-11eb-9ebc-81a9ecc01686.png)

**Comment by webern** [comment]
It would certainly be easier if you could find a Swift implementation of MusicXML. With C++ you will have to write C functions and Objective-C classes to bridge between Swift and the C++ layer. I hope this helps!

**Comment by CoderAndCat** [comment]
Thank you very much for your guidance, but I am still a bit new to the C language. I will use it in my project as you demonstrate. Thanks again, I hope to support cocoapods soon
